elevation_mapping_node:
  ros__parameters:
    pointcloud_channel_fusions:
      rgb: color
      default: average

    image_channel_fusions:
      rgb: color
      default: exponential
      feat_.*: exponential

    subscribers:
      pointcloud_sensor_name:
        topic_name: /realsense/front/camera/depth/color/points
        data_type: pointcloud

    publishers:
      elevation_map_raw:
        layers: [elevation, traversability, variance, rgb]
        basic_layers: [elevation]
        fps: 5.0
      elevation_map_filter:
        layers: [min_filter, smooth, inpaint, elevation]
        basic_layers: [min_filter]
        fps: 5.0

   
 