# A docker-compose must always start with the version tag. "3" is the latest version at this time.
version: "3"
# Use the keyword 'services' to start to define services.
services:  
  elevation_mapping:
    image: "elevation_mapping_cupy_ros2:latest"
    container_name: "elevation_mapping_package"
    env_file: "docker/.ros-env"
    environment:
      environment:
      DISPLAY: $DISPLAY
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
      - elevation_mapping_cupy/elevation_mapping_cupy:/home/ros/workspace/src/elevation_mapping_cupy
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 81:* rmw'
    network_mode: "host"
    privileged: true
    tty: true
    command: " ros2 launch elevation_mapping_cupy elevation_mapping.launch.py"